### PR TITLE
introduce semantic("...")

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by olafurpg** [comment]
Looks great, I fixed the broken test in this diff here: https://github.com/scalameta/paradise/commit/ad5813f74b2161efef9faafd21fd0e75d6c4b84f

Do you want to merge those changes into this PR?

**Comment by olafurpg** [comment]
I just found an issue, it appears that the tests are compiled in the same unit:

```scala
  semantic("class C { def x = 42 }")
  semantic("class C { def x = 43 }")
// output
[info] - class C { def x = 42 }
[info] - class C { def x = 43 } *** FAILED ***
[info]   scalac namer error: C is already defined as class C at source-<ReflectToMeta>,line-1,offset=6 (ConverterSuite.scala:172)
```

**Comment by olafurpg** [comment]
Here is a hack to workaround the test isolation issue: https://github.com/scalameta/paradise/commit/220b76856cdaa67d4637568b84b3e32d7a998e3f

**Comment by xeno-by** [comment]
Yep, let's merge this PR into yours.

**Pull request closed without merging**
