### PR TITLE
Fixing -Yrangepos validation issue

### PR DESCRIPTION
**Pull request by 4lex1v**
Proposed solutions for the issue [#163](https://github.com/scalameta/paradise/issues/163), should also fix [this](https://github.com/scoverage/sbt-scoverage/issues/197) issue for SCoverage plugin

### CODE REVIEW

**Comment by olafurpg** [comment]
Thank you for this contribution! Do you know if it's possible to test this fix? I suspect position handling will change in the future so it would be good prevent the same bug from being reintroduced.

**Comment by 4lex1v** [comment]
@olafurpg this is a good point. Unfortunately i don't know, at this point, since don't have much experience with compiler internals, but i'm ready to investigate it further. I'd appreciate an advice / clue on how to do this

**Comment by xeno-by** [comment]
@4lex1v I guess for now it's good enough if an updated compiler plugin can be manually tested no longer exhibits the problem describes in #163. Testing the presentation compiler is notoriously tricky.

**Comment by 4lex1v** [comment]
@xeno-by it works, i've build a custom version with this fix and use it for now. If there's anything else i need to do to get this merged, please specify

**Comment by xeno-by** [comment]
I'm up for getting this in as is. LGTM.

**Comment by xeno-by** [comment]
Great work! Presentation compiler issues are always challenging, and it's awesome that the fix is so easy.

**Pull request merged**
