### PR TITLE
fix #59

### LINKED ISSUE #59: Macro expansion failes on types parameterized to type constructors
Something like this...
```scala
object Test { 
    @MyAnnotation trait Service[F[_]]
}
```
Results in
```
[error] (tests/test:compileIncremental) org.scalameta.paradise.converters.ConvertException: unexpected error (scroll down the stacktrace to see the cause):
[error] (TypeDef) type _
[error] (TypeDef) type F[_]
[error] (ClassDef) abstract trait Service[F[_]] extends scala.AnyRef
```

### PR DESCRIPTION
**Pull request by Dveim**

### CODE REVIEW

**Comment by olafurpg** [comment]
Just out of curiosity, how do you test this @Dveim ?

**Comment by Dveim** [comment]
Usually I run test file locally and add it to test suite.

Missed second step this time, because this kind of stuff should be tested in `ToMtreeTest`, that does not exist yet. Of course, I'll add appropriate test later.

**Comment by xeno-by** [comment]
LGTM

**Comment by olafurpg** [comment]
Good to know. We definitely need to invest more in unit tests. I'm working on the 4.x branch and I feel very limited by the lack of a comprehensive test suite with structure like in #58

**Comment by olafurpg** [comment]
btw @Dveim there's now a CI server that runs tests on every PR, see #64. It's a 48 core 64gb machine, so tests should run quite fast :)

**Comment by Dveim** [comment]
That's very handy improvement, thanks @olafurpg !

**Pull request merged**
