### PR TITLE
bump scalameta version

### PR DESCRIPTION
**Pull request by iTakeshi**

### CODE REVIEW

**Comment by olafurpg** [comment]
LGTM 👍 Thanks!

**Comment by DavidDudson** [comment]
When was 1.5.0 releases? 

It looks like there's no release on the scalameta github releases. And it probably should be announced to all in gitter. I'll update metabot.

**Comment by xeno-by** [comment]
@DavidDudson It wasn't. `1.5.0.x` is a SNAPSHOT version published in a separate artifact repository.

**Comment by DavidDudson** [comment]
@xeno-by Ah thanks! It all makes sense now

**Pull request merged**
