### PR TITLE
fix #11

### LINKED ISSUE #11: Annotation expansion cannot have arguments
If you try adding arguments in the annotation it fails with `exception during macro expansion, wrong number of arguments`. The `$mods` extracted in the quasiquote also does not have the expansion `@annotation` inside.

I'm assuming that I should be digging around in `Expanders.scala`?

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
review @iTakeshi @DavidDudson @dveim

**Comment by xeno-by** [comment]
Merging this, since there are no comments. If you guys have additional thoughts, let me know here or on gitter.

**Comment by DavidDudson** [comment]
@xeno-by  I apologise, I looked at the code and it was fine. I was going to do some testing first before replying. 

When will this be in 3.0.0 snapshot? I want to start using it :)

**Comment by xeno-by** [comment]
It already is :) I'll now look into the multiple expansion thing.

**Comment by iTakeshi** [comment]
@xeno-by My apologies for the late response. Although the code worked fine, I was just wondering if we could remove the boilerplate: `val q"new $_($greeting)" = this`. I'm still trying on it and I'll send a new PR when it become available.

Thanks

**Comment by xeno-by** [comment]
@iTakeshi I understand that it would be nice to have a simpler syntax, but then it won't quite work with the general design for inline macros described.

For example, what if an inline method defines a def macro and not a macro annotation? In that case, the prefix of the call (the part that corresponds to `this`) may not be of the form `new Something(something)`. Then, the proposed shortcut will no longer work.

Another illustration of this is provided in https://gist.github.com/xeno-by/9d7a709b1ba7c2ee64cfedcc5d264bd5#intuition. What do you think?

**Comment by iTakeshi** [comment]
@xeno-by Even though I understand your concern, but I think it's still worth considering a solution to provide a way to reduce boilerplates, especially for this case because annotation macro is one of the most broadly used form of macro implementation. Simpler syntax also encourage users to upgrade their code to use new style inline macros instead of legacy blackbox/whitebox.

I'm racking my brain to find an ideal solution which solves both my concern: reducing boilerplates and your concern: generality.

**Pull request merged**
